# Gauss-Legendre quadrature on [-1, 1], generated by the Golub-Welsch
# construction. For orthonormal Legendre polynomials the Jacobi matrix has
# zero diagonal and off-diagonal entries i / sqrt(4*i^2 - 1). Its eigenvalues
# are the nodes; twice the squared first eigenvector components are weights.
# Cache by rule size: likelihood evaluations repeatedly use 12 or 16 nodes.
.gauss_legendre <- local({
  rules <- new.env(parent = emptyenv())
  function(n) {
    if (!is.numeric(n) || length(n) != 1L || !is.finite(n) ||
        n < 1 || n != floor(n) || n > .Machine$integer.max) {
      stop("n must be a positive integer")
    }
    n <- as.integer(n)
    key <- as.character(n)
    if (!is.null(rules[[key]])) return(rules[[key]])

    jacobi <- matrix(0, n, n)
    if (n > 1L) {
      i <- seq_len(n - 1L)
      off <- i / sqrt(4 * i^2 - 1)
      jacobi[cbind(i, i + 1L)] <- off
      jacobi[cbind(i + 1L, i)] <- off
    }
    eig <- eigen(jacobi, symmetric = TRUE)
    index <- order(eig$values)
    rule <- list(nodes = eig$values[index],
                 weights = 2 * eig$vectors[1L, index]^2)
    rules[[key]] <- rule
    rule
  }
})
